### PR TITLE
trying to improve some code

### PR DESCRIPTION
**Pull request by zserik**

### CODE REVIEW

**Comment by jjl** [comment]
I was going to close this because I thought it was related to #1 , but I see you did quite a lot more. Sorry about that!

Most of the PR is no longer applicable because I've basically rewritten it, however:
* I also noticed the waiting benchmark was incredibly dumb and fixed it.
* If you wanted to bring `SenderWait` back again, I'd be open to it, if you returned it from the function instead of it being an async function (the downside of an async function is being unable to name it under it under stable rust). Currently we use `poll_fn` from [futures-micro](https://github.com/irrustible/futures-micro) and lack this convenience.

Thanks!

**Comment by zserik** [comment]
@jil I think my main incentive for `SenderWait` was that directly writing a poll fn allowed me to get rid of `delay::delay` and the `poll_fn` hack, and I found it a bit cleaner than trying to re-wrap it inside a `poll_fn` call... but that is objectionable...

**Comment by zserik** [comment]
I close this for now and if I find some places in the new code which may be improvable, I'll open a new PR for thar.

**Comment by jjl** [comment]
I'd be disappointed if you didn't find some places in the new code to improve tbh. Except I also know very much how tedious microbenchmarking is. I will invite you to my private async benchmarking repository as I've been using these to guide the new implementation.

**Pull request closed without merging**
