### PR TITLE
fix auto trait impl Send and Sync

### LINKED ISSUE #21: Send Sender/Reciever<T> needs T: Sync
I want `Sender/Receiver<T>` to implement `Send` without `T` having to implement `Sync`. It seems that the autotrait does it automatically.

https://docs.rs/async-oneshot/latest/async_oneshot/struct.Receiver.html#impl-Send 
https://docs.rs/async-oneshot/latest/async_oneshot/struct.Sender.html#impl-Send

### PR DESCRIPTION
**Pull request by zzau13**
Fixes #21

### CODE REVIEW

**Comment by jjl** [comment]
i'll merge it if you like, but there's a bigger issue with the atomics i've just been unmotivated to work on. i'm a bit surprised people are still using this actually, maybe i should yank it til i get around to fixing it.

**Comment by botika** [comment]
I was just testing. I've read. Where I am using it it seems to work fine. Can you tell me a little more about this issue and I'll try to solve it.

**Comment by jjl** [comment]
It looks like i already started to refactor it a bit on my local copy. As it happens i have some paperwork to procrastinate this morning, so i'll have another go :sweat_smile:

**Comment by botika** [comment]
Thank you very much, if you need anything do not hesitate to tell me. Good luck with the refactor.

**Comment by jjl** [comment]
I put in some time, but my brain isn't really there and i have to figure out which of the handful of approaches that occurred to me today to choose.

But i'll try and do some more on it soon.

**Pull request merged**
